### ISSUE TITLE
Not visible in Preview mode of Andorid Studio for xml.

### ISSUE THREAD

**Issue by prajwalmw** [3llomi/CircularStatusView#11]
Have been using the latest version itself. However when using it in xml the preview is not showing up and an error is populating in the preview mode:

![image](https://user-images.githubusercontent.com/20842086/200487209-1c2d0a5e-d902-44b9-aa1b-29515ff94d88.png)

**Comment by 3llomi** [comment]
Fixed with V1.0.3 🎉
