### ISSUE TITLE
Question: Make the seperation straight

### ISSUE THREAD

**Issue by PRobi23** [3llomi/CircularStatusView#3]
Hi,

I would like to use your library with more colors. Is there any possibility to have a straight separation instead of rounding?
![Screenshot_2020-04-20-09-55-43-269_hu etitan instructor staging](https://user-images.githubusercontent.com/8104926/79748595-febf8800-830d-11ea-8c15-c28e60a0106e.jpg)

I would like to look like this:
<img width="371" alt="Screenshot 2020-04-20 at 13 51 59" src="https://user-images.githubusercontent.com/8104926/79748694-23b3fb00-830e-11ea-9f2a-5b5fe476eb4f.png">

Thanks!

**Comment by 3llomi** [comment]
Hey @PRobi23 ,
you can set a Custom Paint like this
```java
  @NonNull
    private Paint getPaint() {
        Paint paint = new Paint();
        paint.setColor(portionColor);
        paint.setStyle(Paint.Style.STROKE);
        paint.setAntiAlias(true);
        paint.setStrokeWidth(portionWidth);
        return paint;
    }
```
then assign it 
```java
circularStatusView.setCustomPaint(getPaint())
```

let me know how it goes.

**Comment by PRobi23** [comment]
Hey @3llomi  it seems like it's okay.
I added like this (I'm writing the app in Kotlin).
```kotlin
private fun getPaint(): Paint {
        return Paint().also {
            it.style = Paint.Style.STROKE
            it.isAntiAlias = true
            it.strokeWidth = 16F
            it.strokeCap = Paint.Cap.SQUARE
        }
    }
```
