### ISSUE TITLE
setting portion width programmatically creates rounded square

### ISSUE THREAD

**Issue by pavan555** [3llomi/CircularStatusView#5]
This is great library and I found an issue that the setting portion width programmatically creates rounded square like below

### Working Code 
```java
circularStatusView.setPortionsCount(1);            
//circularStatusView.setPortionWidth(2f);
```

**Output**

![Screenshot_20201029_174602](https://user-images.githubusercontent.com/25476729/97573117-48043900-1a0f-11eb-9f7d-456e11f6a476.png)

### Bug Code
```java
circularStatusView.setPortionsCount(1);            
circularStatusView.setPortionWidth(2f);
```

**Output**

![Screenshot_20201029_174652](https://user-images.githubusercontent.com/25476729/97573155-55b9be80-1a0f-11eb-94d6-35c44995e6d0.png)

**Comment by 3llomi** [comment]
Hi, @pavan555 

i believe adding some padding would solve this issue? please give it a shot.
