### ISSUE TITLE
Jcentre repository is shut down

### ISSUE THREAD

**Issue by VaibhavNerd** [3llomi/CircularStatusView#7]
As in new update of Android studio  4.2.1 Jcentre repository is not considerd so we could not access your library and it is giving a error 
plzz shift to maven central and update your repository ..

First I was getting this error
 ![2021-05-31 (1)](https://user-images.githubusercontent.com/75988605/120119393-23468e80-c1b5-11eb-8799-9f249c31a34c.png)
 but after removing jcentre usage in build script 
I could not access your code and library usage and getting this error 
then I read about this that the developer who were using Jcentre respository have to shift to mavencentral
![2021-05-31](https://user-images.githubusercontent.com/75988605/120119346-e24e7a00-c1b4-11eb-8040-46f69ae1c2a1.png)

-

**Comment by DavinderHanda** [comment]
Same issues faced .. ...

**Comment by VaibhavNerd** [comment]
> Same issues faced .. ...

i got the solution just go in build gradle project and lower your tools build gradle version 
It worked for me  classpath "com.android.tools.build:gradle:4.1.1" i tried this version

**Comment by DavinderHanda** [comment]
> > Same issues faced .. ...
> 
> i got the solution just go in build gradle project and lower your tools build gradle version
> It worked for me classpath "com.android.tools.build:gradle:4.1.1" i tried this version

not working this .....

**Comment by 3llomi** [comment]
Migrated to JitPack

**Comment by VaibhavNerd** [comment]
> Migrated to JitPack

Thnxx

**Comment by inder18112000** [comment]
Still not working after migrate to jitpack
