### ISSUE TITLE
I cannot use this library on my project

### ISSUE THREAD

**Issue by Abisayo1** [3llomi/CircularStatusView#8]
Good day bro

I am trying to use this library on my WhatsApp application but it is not working. My guess is that this library has been depreciated. If you can help me to implement it on my Whatsapp clone app on my GitHub repository, I will be so grateful:

https://github.com/Abisayo1/WhatsApp-Clone

The name of the layout file is fragment_status.xml

**Comment by 3llomi** [comment]
Hey @Abisayo1 
What error do you get?

**Comment by ghost** [comment]
After adding the dependency it's not working in XML layout means unable to add on xml

**Comment by 3llomi** [comment]
Please make sure to add the latest version using JitPack
`  implementation 'com.github.3llomi:CircularStatusView:V1.0.2'`
