### ISSUE TITLE
I got error after add this dependency....

### ISSUE THREAD

**Issue by Dmodi1004** [3llomi/CircularStatusView#9]
When I implement this dependency I got this error:~ Duplicate class found

Duplicate class android.support.v4.os.ResultReceiver$MyRunnable found in modules core-1.7.0-runtime (androidx.core:core:1.7.0) and support-compat-27.1.1-runtime (com.android.support:support-compat:27.1.1)

That's why I didn't use this feature....
Please help me....

**Comment by tergesa** [comment]
I had the same error and I fixed it by adding this code to the **gradle.properties** file.

`android.enableJetifier=true`
